import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="px-6 py-4 bg-slate-50">
          <div className="flex items-center gap-2">
            {/* Logo */}
            <h1 className="text-xl font-semibold text-slate-900">Recall Hub</h1>
          </div>
        </header>
        {/* Main Content */}
        {children}
        {/* Footer */}
        <footer className="px-6 py-8 text-center bg-slate-50">
          <p className="text-sm text-slate-500">
            © 2025 Recall Hub. A tool for better learning.
          </p>
        </footer>
      </body>
    </html>
  );
}
